---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- include_tasks: '{{ceph_pkg_mgr}}-setup.yml'
  when: ceph_pkg_mgr is defined
    
- name: install ceph pkgs
  become: yes
  become_user: root
  with_items: '{{ceph_pkgs | default([])}}'
  package:
    name: '{{item}}'
    state: present

  
