---
- name: install rpm key
  become: yes
  become_user: root
  rpm_key:
    key: '{{ ceph_key_url }}'
    state: present
- name: add yum pkgs
  with_items:
    - name: ceph-basearch
      description: Ceph packages for $basearch
      baseurl_suffix: $basearch
      enabled: yes
    - name: ceph-noarch
      description: Ceph noarch packages
      baseurl_suffix: noarch
      enabled: yes
    - name: ceph-srpms
      description: Ceph source packages
      baseurl_suffix: SRPMS
      enabled: no
  yum_repository:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    baseurl: '{{ ceph_baseurl_base }}/{{ item.baseurl_suffix }}'
    enabled: '{{ item.enabled }}'
    priority: '2'
    gpgcheck: yes
    gpgkey: '{{ ceph_key_url }}'
