---
- name: install rpm key
  become: yes
  become_user: root
  rpm_key:
    key: '{{ceph_key_url}}'
    state: present

- name: add yum repo conf
  become: yes
  become_user: root
  with_items:
    - f: ceph.repo
      d: /etc/yum/repos.d
      m: 0644
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'
